/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeedbackAnimation: typeof import('./components/ui/FeedbackAnimation.vue')['default']
    ProgressPath: typeof import('./components/ui/ProgressPath.vue')['default']
    QuestionEditor: typeof import('./components/quiz/QuestionEditor.vue')['default']
    QuestionStep: typeof import('./components/quiz/QuestionStep.vue')['default']
    QuizCard: typeof import('./components/quiz/QuizCard.vue')['default']
    QuizForm: typeof import('./components/quiz/QuizForm.vue')['default']
    QuizPlayer: typeof import('./components/quiz/QuizPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreScreen: typeof import('./components/quiz/ScoreScreen.vue')['default']
  }
}
